import type { Metadata } from "next";
import { Zalando_Sans_SemiExpanded } from "next/font/google";
import "./globals.css";

const hostGrotesk = Zalando_Sans_SemiExpanded({
  weight: ["400", "500", "600", "700"],
  variable: "--font-host",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hostGrotesk.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
